// Usages et recommandations extraits automatiquement (bloc complet)
const recommandations = {
  "Vitrine": [
    { nom: "Vinyle transparent brillant", prix: "7.99 € HT/m²", delai: "5 jours", url: "https://signatix.fr/supports/adhesifs?id=8" },
    { nom: "Vinyle Microperforé", prix: "7.99 € HT/m²", delai: "3 jours", url: "https://signatix.fr/supports/adhesifs?id=12" },
    { nom: "Vinyle monomère colle renforcée", prix: "9.99 € HT/m²", delai: "3 jours", url: "https://signatix.fr/supports/adhesifs?id=51" },
    { nom: "Vinyle polymère super tack", prix: "13.99 € HT/m²", delai: "3 jours", url: "https://signatix.fr/supports/adhesifs?id=54" },
    { nom: "Micro ventouse M1 Brillant", prix: "8.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/affiches-films?id=56" },
    { nom: "Micro ventouse M1 Mat", prix: "8.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/affiches-films?id=59" },
    { nom: "Micro ventouse Transparent", prix: "8.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/affiches-films?id=61" },
    { nom: "Microperfore+plastif ultra clear", prix: "29.5 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/adhesifs?id=73" },
    { nom: "Microperforé pose intérieur", prix: "24.8 € HT/m²", delai: "5 jours", url: "https://signatix.fr/supports/adhesifs?id=87" },
    { nom: "Vinyle ultra transparent", prix: "9.99 € HT/m²", delai: "5 jours", url: "https://signatix.fr/supports/adhesifs?id=88" },
    { nom: "Dépoli polymère Air Free", prix: "14.99 € HT/m²", delai: "3 jours", url: "https://signatix.fr/supports/decoration?id=126" }
  ],
  "PLV": [
    { nom: "Film PVC 300 microns", prix: "7.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/affiches-films?id=16" },
    { nom: "Panneau PVC 2mm", prix: "8.55 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/supports-rigides?id=52" },
    { nom: "Panneau PVC 3mm", prix: "12.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/supports-rigides?id=27" },
    { nom: "Panneau PVC 5mm", prix: "16.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/supports-rigides?id=28" },
    { nom: "Panneau PVC 10mm", prix: "33.99 € HT/m²", delai: "5 jours", url: "https://signatix.fr/supports/supports-rigides?id=29" }
  ],
  "Signalétique intérieure": [
    { nom: "Panneau PVC 2mm", prix: "8.55 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/supports-rigides?id=52" },
    { nom: "Panneau PVC 3mm", prix: "12.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/supports-rigides?id=27" },
    { nom: "Panneau PVC 5mm", prix: "16.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/supports-rigides?id=28" },
    { nom: "Panneau PVC 10mm", prix: "33.99 € HT/m²", delai: "5 jours", url: "https://signatix.fr/supports/supports-rigides?id=29" },
    { nom: "Panneau Alu Bond 3mm", prix: "30.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/supports-rigides?id=30" },
    { nom: "Plexi 5mm ", prix: "62.99 € HT/m²", delai: "6 jours", url: "https://signatix.fr/supports/supports-rigides?id=42" },
    { nom: "Plexi 8mm", prix: "98.0 € HT/m²", delai: "6 jours", url: "https://signatix.fr/supports/supports-rigides?id=91" },
    { nom: "Adhésif polymère colle renforcée enlevable", prix: "9.99 € HT/m²", delai: "3 jours", url: "https://signatix.fr/supports/adhesifs?id=136" }
  ],
  "Signalétique extérieure": [
    { nom: "Vinyle polymère", prix: "7.62 € HT/m²", delai: "3 jours", url: "https://signatix.fr/supports/adhesifs?id=9" },
    { nom: "Panneau PVC 2mm", prix: "8.55 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/supports-rigides?id=52" },
    { nom: "Panneau PVC 3mm", prix: "12.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/supports-rigides?id=27" },
    { nom: "Panneau PVC 5mm", prix: "16.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/supports-rigides?id=28" },
    { nom: "Panneau PVC 10mm", prix: "33.99 € HT/m²", delai: "5 jours", url: "https://signatix.fr/supports/supports-rigides?id=29" },
    { nom: "Panneau Alu Bond 3mm", prix: "30.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/supports-rigides?id=30" },
    { nom: "Plexi 5mm ", prix: "62.99 € HT/m²", delai: "6 jours", url: "https://signatix.fr/supports/supports-rigides?id=42" },
    { nom: "Plexi 8mm", prix: "98.0 € HT/m²", delai: "6 jours", url: "https://signatix.fr/supports/supports-rigides?id=91" }
  ],
  "Véhicule": [
    { nom: "Vinyle polymère", prix: "7.62 € HT/m²", delai: "3 jours", url: "https://signatix.fr/supports/adhesifs?id=9" },
    { nom: "Vinyle covering+plastif brillante", prix: "39.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/adhesifs?id=11" },
    { nom: "Magnétique véhicule Laminé", prix: "18.3 € HT/m²", delai: "7 jours", url: "https://signatix.fr/supports/sup-semi-rigides?id=71" },
    { nom: "Microperfore+plastif ultra clear", prix: "29.5 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/adhesifs?id=73" },
    { nom: "Adhésif rétro réfléchissant", prix: "35.6 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/adhesifs?id=83" }
  ],
  "Décoration intérieure": [
    { nom: "Micro ventouse M1 Brillant", prix: "8.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/affiches-films?id=56" },
    { nom: "Micro ventouse M1 Mat", prix: "8.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/affiches-films?id=59" },
    { nom: "Micro ventouse Transparent", prix: "8.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/affiches-films?id=61" },
    { nom: "Toile adhésive repositionnable", prix: "19.6 € HT/m²", delai: "6 jours", url: "https://signatix.fr/supports/baches-toiles?id=76" },
    { nom: "Micro ventouse Transparent", prix: "8.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/decoration?id=121" },
    { nom: "Toile Canvas Metallic Gold", prix: "30.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/decoration?id=125" },
    { nom: "Toile Simili Cuir", prix: "16.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/decoration?id=127" },
    { nom: "Papier Peint 150gr. sans pvc", prix: "6.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/decoration?id=129" },
    { nom: "Papier peint pré-encollé ", prix: "16.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/decoration?id=139" }
  ],
  "Evénementiel/Salon": [
    { nom: "Bâche éco 350g", prix: "4.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/baches-toiles?id=18" },
    { nom: "Bâche 450g M1", prix: "7.9 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/baches-toiles?id=21" },
    { nom: "Bâche 510g enduite", prix: "6.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/baches-toiles?id=20" },
    { nom: "Bâche grille mesh", prix: "6.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/baches-toiles?id=19" },
    { nom: "Bâche 650g blockout M1 imp.R°", prix: "10.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/baches-toiles?id=22" },
    { nom: "Bâche 650g blockout M1 imp.R°V°", prix: "26.8 € HT/m²", delai: "5 jours", url: "https://signatix.fr/supports/baches-toiles?id=45" },
    { nom: "Panneau PVC 2mm", prix: "8.55 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/supports-rigides?id=52" },
    { nom: "Panneau PVC 3mm", prix: "12.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/supports-rigides?id=27" },
    { nom: "Panneau PVC 5mm", prix: "16.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/supports-rigides?id=28" },
    { nom: "Panneau PVC 10mm", prix: "33.99 € HT/m²", delai: "5 jours", url: "https://signatix.fr/supports/supports-rigides?id=29" },
    { nom: "Panneau Alu Bond 3mm", prix: "30.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/supports-rigides?id=30" },
    { nom: "Plexi 5mm ", prix: "62.99 € HT/m²", delai: "6 jours", url: "https://signatix.fr/supports/supports-rigides?id=42" },
    { nom: "Plexi 8mm", prix: "98.0 € HT/m²", delai: "6 jours", url: "https://signatix.fr/supports/supports-rigides?id=91" },
    { nom: "Toile blockout Black.tex®", prix: "15.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/baches-toiles?id=131" },
    { nom: "Toile Lin Coton intissée à encoller", prix: "21.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/decoration?id=128" }
  ],
  "Usage économique": [
    { nom: "Panneau alvéolé 3mm ", prix: "3.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/supports-rigides?id=141" },
    { nom: "Panneau alvéolé 3.5 mm", prix: "4.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/supports-rigides?id=63" },
    { nom: "Panneau alvéolé 5mm", prix: "13.49 € HT/m²", delai: "5 jours", url: "https://signatix.fr/supports/supports-rigides?id=72" },
    { nom: "Panneau alvéolé 8mm", prix: "18.89 € HT/m²", delai: "6 jours", url: "https://signatix.fr/supports/supports-rigides?id=26" },
    { nom: "Vinyle monomère", prix: "4.3 € HT/m²", delai: "3 jours", url: "https://signatix.fr/supports/adhesifs?id=5" },
    { nom: "Vinyle transparent brillant", prix: "7.99 € HT/m²", delai: "5 jours", url: "https://signatix.fr/supports/adhesifs?id=8" },
    { nom: "Vinyle Microperforé", prix: "7.99 € HT/m²", delai: "3 jours", url: "https://signatix.fr/supports/adhesifs?id=12" },
    { nom: "Papier dos bleu 120g ", prix: "2.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/affiches-films?id=13" },
    { nom: "Papier 130gr CB ", prix: "3.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/affiches-films?id=53" },
    { nom: "Papier épais 150g ", prix: "4.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/affiches-films?id=130" },
    { nom: "Papier épais 200g ", prix: "4.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/affiches-films?id=14" },
    { nom: "Papier épais 200g + lamination R ", prix: "8.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/affiches-films?id=62" },
    { nom: "Film PVC 300 microns", prix: "7.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/affiches-films?id=16" },
    { nom: "Bâche éco 350g", prix: "4.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/baches-toiles?id=18" },
    { nom: "Panneau PVC 2mm", prix: "8.55 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/supports-rigides?id=52" },
    { nom: "Panneau PVC 3mm", prix: "12.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/supports-rigides?id=27" },
    { nom: "Panneau PVC 5mm", prix: "16.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/supports-rigides?id=28" },
    { nom: "Panneau PVC 10mm", prix: "33.99 € HT/m²", delai: "5 jours", url: "https://signatix.fr/supports/supports-rigides?id=29" },
    { nom: "Micro ventouse M1 Brillant", prix: "8.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/affiches-films?id=56" },
    { nom: "Micro ventouse M1 Mat", prix: "8.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/affiches-films?id=59" },
    { nom: "Micro ventouse Transparent", prix: "8.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/affiches-films?id=61" }
  ],
    "Usage premium": [
    { nom: "Vinyle polymère", prix: "7.62 € HT/m²", delai: "3 jours", url: "https://signatix.fr/supports/adhesifs?id=9" },
    { nom: "Vinyle covering+plastif brillante", prix: "39.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/adhesifs?id=11" },
    { nom: "Bâche grille mesh", prix: "6.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/baches-toiles?id=19" },
    { nom: "Bâche 450g M1", prix: "7.9 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/baches-toiles?id=21" },
    { nom: "Bâche 510g enduite", prix: "6.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/baches-toiles?id=20" },
    { nom: "Bâche 650g blockout M1 imp.R°", prix: "10.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/baches-toiles?id=22" },
    { nom: "Bâche 650g blockout M1 imp.R°V°", prix: "26.8 € HT/m²", delai: "5 jours", url: "https://signatix.fr/supports/baches-toiles?id=45" },
    { nom: "Panneau Alu Bond 3mm", prix: "30.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/supports-rigides?id=30" },
    { nom: "Plexi 5mm ", prix: "62.99 € HT/m²", delai: "6 jours", url: "https://signatix.fr/supports/supports-rigides?id=42" },
    { nom: "Plexi 8mm", prix: "98.0 € HT/m²", delai: "6 jours", url: "https://signatix.fr/supports/supports-rigides?id=91" },
    { nom: "Toile blockout Black.tex®", prix: "15.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/baches-toiles?id=131" },
    { nom: "Toile Canvas Metallic Gold", prix: "30.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/decoration?id=125" },
    { nom: "Toile Simili Cuir", prix: "16.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/decoration?id=127" },
    { nom: "Toile Lin Coton intissée à encoller", prix: "21.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/decoration?id=128" },
    { nom: "Vinyle polymère super tack", prix: "13.99 € HT/m²", delai: "3 jours", url: "https://signatix.fr/supports/adhesifs?id=54" },
    { nom: "Galazzi 300 microns", prix: "11.99 € HT/m²", delai: "7 jours", url: "https://signatix.fr/supports/sup-semi-rigides?id=77" },
    { nom: "Galazzi 500 microns", prix: "12.99 € HT/m²", delai: "7 jours", url: "https://signatix.fr/supports/sup-semi-rigides?id=64" },
    { nom: "Magnétique véhicule Laminé", prix: "18.3 € HT/m²", delai: "7 jours", url: "https://signatix.fr/supports/sup-semi-rigides?id=71" },
    { nom: "Microperfore+plastif ultra clear", prix: "29.5 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/adhesifs?id=73" },
    { nom: "Revêtement de sol", prix: "25.25 € HT/m²", delai: "6 jours", url: "https://signatix.fr/supports/sup-semi-rigides?id=86" },
    { nom: "Microperforé pose intérieur", prix: "24.8 € HT/m²", delai: "5 jours", url: "https://signatix.fr/supports/adhesifs?id=87" },
    { nom: "Vinyle ultra transparent", prix: "9.99 € HT/m²", delai: "5 jours", url: "https://signatix.fr/supports/adhesifs?id=88" },
    { nom: "Papier Peint 150gr. sans pvc", prix: "6.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/decoration?id=129" },
    { nom: "Papier peint pré-encollé ", prix: "16.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/decoration?id=139" },
    { nom: "Adhésif polymère transparent colle renforcée", prix: "14.99 € HT/m²", delai: "5 jours", url: "https://signatix.fr/supports/adhesifs?id=134" },
    { nom: "Adhésif polymère colle renforcée enlevable", prix: "9.99 € HT/m²", delai: "3 jours", url: "https://signatix.fr/supports/adhesifs?id=136" },
    { nom: "Adhésif polymère 100 % opaque épais", prix: "15.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/adhesifs?id=138" },
    { nom: "Adhésif polymère transparent colle renforcée", prix: "16.99 € HT/m²", delai: "6 jours", url: "https://signatix.fr/supports/stickers?id=140" }
  ],
  "Usage écologique": [
    { nom: "Panneau alvéolé 3mm ", prix: "3.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/supports-rigides?id=141" },
    { nom: "Panneau alvéolé 3.5 mm", prix: "4.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/supports-rigides?id=63" },
    { nom: "Panneau alvéolé 5mm", prix: "13.49 € HT/m²", delai: "5 jours", url: "https://signatix.fr/supports/supports-rigides?id=72" },
    { nom: "Panneau alvéolé 8mm", prix: "18.89 € HT/m²", delai: "6 jours", url: "https://signatix.fr/supports/supports-rigides?id=26" },
    { nom: "Backlit satin diffusant 130g", prix: "9.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/affiches-films?id=15" },
    { nom: "Toile adhésive repositionnable", prix: "19.6 € HT/m²", delai: "6 jours", url: "https://signatix.fr/supports/baches-toiles?id=76" },
    { nom: "Toile Canvas Metallic Gold", prix: "30.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/decoration?id=125" },
    { nom: "Toile Simili Cuir", prix: "16.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/decoration?id=127" },
    { nom: "Toile Lin Coton intissée à encoller", prix: "21.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/decoration?id=128" },
    { nom: "Papier Peint 150gr. sans pvc", prix: "6.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/decoration?id=129" },
    { nom: "Toile blockout Black.tex®", prix: "15.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/baches-toiles?id=131" },
    { nom: "Papier peint pré-encollé ", prix: "16.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/decoration?id=139" }
  ],
  "Affichage chantier": [
    { nom: "Panneau alvéolé 3mm ", prix: "3.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/supports-rigides?id=141" },
    { nom: "Panneau alvéolé 3.5 mm", prix: "4.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/supports-rigides?id=63" },
    { nom: "Panneau alvéolé 5mm", prix: "13.49 € HT/m²", delai: "5 jours", url: "https://signatix.fr/supports/supports-rigides?id=72" },
    { nom: "Panneau alvéolé 8mm", prix: "18.89 € HT/m²", delai: "6 jours", url: "https://signatix.fr/supports/supports-rigides?id=26" },
    { nom: "Bâche éco 350g", prix: "4.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/baches-toiles?id=18" },
    { nom: "Bâche grille mesh", prix: "6.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/baches-toiles?id=19" },
    { nom: "Bâche 450g M1", prix: "7.9 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/baches-toiles?id=21" },
    { nom: "Bâche 650g blockout M1 imp.R°", prix: "10.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/baches-toiles?id=22" },
    { nom: "Bâche 650g blockout M1 imp.R°V°", prix: "26.8 € HT/m²", delai: "5 jours", url: "https://signatix.fr/supports/baches-toiles?id=45" }
  ],
  "Plaque professionnelle": [
    { nom: "Panneau Alu Bond 3mm", prix: "30.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/supports-rigides?id=30" },
    { nom: "Plexi 5mm ", prix: "62.99 € HT/m²", delai: "6 jours", url: "https://signatix.fr/supports/supports-rigides?id=42" },
    { nom: "Plexi 8mm", prix: "98.0 € HT/m²", delai: "6 jours", url: "https://signatix.fr/supports/supports-rigides?id=91" }
  ],
  "Goodies": [
    { nom: "Plexi 5mm ", prix: "62.99 € HT/m²", delai: "6 jours", url: "https://signatix.fr/supports/supports-rigides?id=42" },
    { nom: "Plexi 8mm", prix: "98.0 € HT/m²", delai: "6 jours", url: "https://signatix.fr/supports/supports-rigides?id=91" },
    { nom: "Galazzi 500 microns", prix: "12.99 € HT/m²", delai: "7 jours", url: "https://signatix.fr/supports/sup-semi-rigides?id=64" },
    { nom: "Galazzi 300 microns", prix: "11.99 € HT/m²", delai: "7 jours", url: "https://signatix.fr/supports/sup-semi-rigides?id=77" },
    { nom: "Magnet intérieur 350 microns", prix: "15.99 € HT/m²", delai: "6 jours", url: "https://signatix.fr/supports/stickers?id=84" },
    { nom: "Revêtement de sol", prix: "25.25 € HT/m²", delai: "6 jours", url: "https://signatix.fr/supports/sup-semi-rigides?id=86" }
  ],
  "Communication sol": [
    { nom: "Vinyle polymère super tack", prix: "13.99 € HT/m²", delai: "3 jours", url: "https://signatix.fr/supports/adhesifs?id=54" },
    { nom: "Adhésif polymère colle renforcée enlevable", prix: "9.99 € HT/m²", delai: "3 jours", url: "https://signatix.fr/supports/adhesifs?id=136" },
    { nom: "Adhésif polymère 100 % opaque épais", prix: "15.99 € HT/m²", delai: "4 jours", url: "https://signatix.fr/supports/adhesifs?id=138" },
    { nom: "Revêtement de sol", prix: "25.25 € HT/m²", delai: "6 jours", url: "https://signatix.fr/supports/sup-semi-rigides?id=86" }
  ]
};

const vignettesProduits = {
  "https://signatix.fr/supports/adhesifs?id=5": "https://signatix.fr/img/supports/5/mini.jpg",
  "https://signatix.fr/supports/adhesifs?id=7": "https://signatix.fr/img/supports/7/mini.jpg",
  "https://signatix.fr/supports/adhesifs?id=8": "https://signatix.fr/img/supports/8/mini.jpg",
  "https://signatix.fr/supports/adhesifs?id=9": "https://signatix.fr/img/supports/9/mini.jpg",
  "https://signatix.fr/supports/adhesifs?id=10": "https://signatix.fr/img/supports/10/mini.jpg",
  "https://signatix.fr/supports/adhesifs?id=11": "https://signatix.fr/img/supports/11/mini.jpg",
  "https://signatix.fr/supports/adhesifs?id=12": "https://signatix.fr/img/supports/12/mini.jpg",
  "https://signatix.fr/supports/affiches-films?id=13": "https://signatix.fr/img/supports/13/mini.jpg",
  "https://signatix.fr/supports/affiches-films?id=14": "https://signatix.fr/img/supports/14/mini.jpg",
  "https://signatix.fr/supports/affiches-films?id=15": "https://signatix.fr/img/supports/15/mini.jpg",
  "https://signatix.fr/supports/affiches-films?id=16": "https://signatix.fr/img/supports/16/mini.jpg",
  "https://signatix.fr/supports/baches-toiles?id=18": "https://signatix.fr/img/supports/18/mini.jpg",
  "https://signatix.fr/supports/baches-toiles?id=19": "https://signatix.fr/img/supports/19/mini.jpg",
  "https://signatix.fr/supports/baches-toiles?id=20": "https://signatix.fr/img/supports/20/mini.jpg",
  "https://signatix.fr/supports/baches-toiles?id=21": "https://signatix.fr/img/supports/21/mini.jpg",
  "https://signatix.fr/supports/baches-toiles?id=22": "https://signatix.fr/img/supports/22/mini.jpg",
  "https://signatix.fr/supports/baches-toiles?id=23": "https://signatix.fr/img/supports/23/mini.jpg",
  "https://signatix.fr/supports/stickers?id=24": "https://signatix.fr/img/supports/24/mini.jpg",
  "https://signatix.fr/supports/stickers?id=25": "https://signatix.fr/img/supports/25/mini.jpg",
  "https://signatix.fr/supports/supports-rigides?id=26": "https://signatix.fr/img/supports/26/mini.jpg",
  "https://signatix.fr/supports/supports-rigides?id=27": "https://signatix.fr/img/supports/27/mini.jpg",
  "https://signatix.fr/supports/supports-rigides?id=28": "https://signatix.fr/img/supports/28/mini.jpg",
  "https://signatix.fr/supports/supports-rigides?id=29": "https://signatix.fr/img/supports/29/mini.jpg",
  "https://signatix.fr/supports/supports-rigides?id=30": "https://signatix.fr/img/supports/30/mini.jpg",
  "https://signatix.fr/supports/supports-rigides?id=42": "https://signatix.fr/img/supports/42/mini.jpg",
  "https://signatix.fr/supports/baches-toiles?id=45": "https://signatix.fr/img/supports/45/mini.jpg",
  "https://signatix.fr/supports/baches-toiles?id=46": "https://signatix.fr/img/supports/46/mini.jpg",
  "https://signatix.fr/supports/baches-toiles?id=48": "https://signatix.fr/img/supports/48/mini.jpg",
  "https://signatix.fr/supports/adhesifs?id=51": "https://signatix.fr/img/supports/51/mini.jpg",
  "https://signatix.fr/supports/supports-rigides?id=52": "https://signatix.fr/img/supports/52/mini.jpg",
  "https://signatix.fr/supports/affiches-films?id=53": "https://signatix.fr/img/supports/53/mini.jpg",
  "https://signatix.fr/supports/adhesifs?id=54": "https://signatix.fr/img/supports/54/mini.jpg",
  "https://signatix.fr/supports/affiches-films?id=56": "https://signatix.fr/img/supports/56/mini.jpg",
  "https://signatix.fr/supports/affiches-films?id=59": "https://signatix.fr/img/supports/59/mini.jpg",
  "https://signatix.fr/supports/affiches-films?id=61": "https://signatix.fr/img/supports/61/mini.jpg",
  "https://signatix.fr/supports/affiches-films?id=62": "https://signatix.fr/img/supports/62/mini.jpg",
  "https://signatix.fr/supports/supports-rigides?id=63": "https://signatix.fr/img/supports/63/mini.jpg",
  "https://signatix.fr/supports/sup-semi-rigides?id=64": "https://signatix.fr/img/supports/64/mini.jpg",
  "https://signatix.fr/supports/sup-semi-rigides?id=65": "https://signatix.fr/img/supports/65/mini.jpg",
  "https://signatix.fr/supports/sup-semi-rigides?id=66": "https://signatix.fr/img/supports/66/mini.jpg",
  "https://signatix.fr/supports/sup-semi-rigides?id=71": "https://signatix.fr/img/supports/71/mini.jpg",
  "https://signatix.fr/supports/supports-rigides?id=72": "https://signatix.fr/img/supports/72/mini.jpg",
  "https://signatix.fr/supports/adhesifs?id=73": "https://signatix.fr/img/supports/73/mini.jpg",
  "https://signatix.fr/supports/adhesifs?id=74": "https://signatix.fr/img/supports/74/mini.jpg",
  "https://signatix.fr/supports/baches-toiles?id=76": "https://signatix.fr/img/supports/76/mini.jpg",
  "https://signatix.fr/supports/sup-semi-rigides?id=77": "https://signatix.fr/img/supports/77/mini.jpg",
  "https://signatix.fr/supports/sup-semi-rigides?id=78": "https://signatix.fr/img/supports/78/mini.jpg",
  "https://signatix.fr/supports/supports-rigides?id=79": "https://signatix.fr/img/supports/79/mini.jpg",
  "https://signatix.fr/supports/stickers?id=80": "https://signatix.fr/img/supports/80/mini.jpg",
  "https://signatix.fr/supports/stickers?id=81": "https://signatix.fr/img/supports/81/mini.jpg",
  "https://signatix.fr/supports/stickers?id=82": "https://signatix.fr/img/supports/82/mini.jpg",
  "https://signatix.fr/supports/adhesifs?id=83": "https://signatix.fr/img/supports/83/mini.jpg",
  "https://signatix.fr/supports/stickers?id=84": "https://signatix.fr/img/supports/84/mini.jpg",
  "https://signatix.fr/supports/stickers?id=85": "https://signatix.fr/img/supports/85/mini.jpg",
  "https://signatix.fr/supports/sup-semi-rigides?id=86": "https://signatix.fr/img/supports/86/mini.jpg",
  "https://signatix.fr/supports/adhesifs?id=87": "https://signatix.fr/img/supports/87/mini.jpg",
  "https://signatix.fr/supports/adhesifs?id=88": "https://signatix.fr/img/supports/88/mini.jpg",
  "https://signatix.fr/supports/adhesifs?id=89": "https://signatix.fr/img/supports/89/mini.jpg",
  "https://signatix.fr/supports/stickers?id=90": "https://signatix.fr/img/supports/90/mini.jpg",
  "https://signatix.fr/supports/supports-rigides?id=91": "https://signatix.fr/img/supports/91/mini.jpg",
  "https://signatix.fr/supports/supports-rigides?id=92": "https://signatix.fr/img/supports/92/mini.jpg",
  "https://signatix.fr/supports/baches-toiles?id=94": "https://signatix.fr/img/supports/94/mini.jpg",
  "https://signatix.fr/supports/supports-rigides?id=104": "https://signatix.fr/img/supports/104/mini.jpg",
  "https://signatix.fr/supports/affiches-films?id=105": "https://signatix.fr/img/supports/105/mini.jpg",
  "https://signatix.fr/supports/affiches-films?id=106": "https://signatix.fr/img/supports/106/mini.jpg",
  "https://signatix.fr/supports/sup-semi-rigides?id=113": "https://signatix.fr/img/supports/113/mini.jpg",
  "https://signatix.fr/supports/adhesifs?id=117": "https://signatix.fr/img/supports/117/mini.jpg",
  "https://signatix.fr/supports/baches-toiles?id=120": "https://signatix.fr/img/supports/120/mini.jpg",
  "https://signatix.fr/supports/decoration?id=121": "https://signatix.fr/img/supports/121/mini.jpg",
  "https://signatix.fr/supports/decoration?id=122": "https://signatix.fr/img/supports/122/mini.jpg",
  "https://signatix.fr/supports/decoration?id=124": "https://signatix.fr/img/supports/124/mini.jpg",
  "https://signatix.fr/supports/decoration?id=125": "https://signatix.fr/img/supports/125/mini.jpg",
  "https://signatix.fr/supports/decoration?id=126": "https://signatix.fr/img/supports/126/mini.jpg",
  "https://signatix.fr/supports/decoration?id=127": "https://signatix.fr/img/supports/127/mini.jpg",
  "https://signatix.fr/supports/decoration?id=128": "https://signatix.fr/img/supports/128/mini.jpg",
  "https://signatix.fr/supports/decoration?id=129": "https://signatix.fr/img/supports/129/mini.jpg",
  "https://signatix.fr/supports/affiches-films?id=130": "https://signatix.fr/img/supports/130/mini.jpg",
  "https://signatix.fr/supports/baches-toiles?id=131": "https://signatix.fr/img/supports/131/mini.jpg",
  "https://signatix.fr/supports/adhesifs?id=134": "https://signatix.fr/img/supports/134/mini.jpg",
  "https://signatix.fr/supports/adhesifs?id=136": "https://signatix.fr/img/supports/136/mini.jpg",
  "https://signatix.fr/supports/adhesifs?id=138": "https://signatix.fr/img/supports/138/mini.jpg",
  "https://signatix.fr/supports/decoration?id=139": "https://signatix.fr/img/supports/139/mini.jpg",
  "https://signatix.fr/supports/stickers?id=140": "https://signatix.fr/img/supports/140/mini.jpg",
  "https://signatix.fr/supports/supports-rigides?id=141": "https://signatix.fr/img/supports/141/mini.jpg",
};
